export default {
  apiUrl: 'https://cpdevcp.cloudplusstaging.review/CloudPlus.Api/api/',
  authConfig: {
    authority: 'https://cpdevcp.cloudplusstaging.review/CloudPlus.Authentication.Api/cloudplus/',
    clientId: 'cloudplusAdminPortal',
    redurectUri: `${window.location.origin}/static/callback.html`,
    silent_redirect_uri: `${window.location.origin}/static/silent.html`,
    expiringNotificationTime: 10,
    automaticSilentRenew: true,
    responseType: 'id_token token',
    scope: 'openid read',
    postLogoutRedirectUri: window.location.origin,
    forgotPasswordRoute: 'forgotPassword',
    changePasswordRoute: 'changePassword',
    activeDirectoryEndpoint: 'https://192.168.73.175:8585/',
  },
  API_VerifyRecaptcha: 'recaptcha',
  // Users List Form Settings
  usersPerPage: 10,
  editUserRoute: 'users/edit',
  createNewUserRoute: 'users/create',
  externalResellerSignupForm: 'externalResellerSignupForm',
  externalCustomerSignupForm: 'externalCustomerSignupForm',
  externalResellerIframe: '<iframe width="100%" height="100%" src="https://cpdevcp.cloudplusstaging.review/#/external-reseller-signup-form?parentId=uniqueIdentifier&brandColor=%23uniqueColor" frameborder="0" seamless="seamless"></iframe>',
  externalCustomerIframe: '<iframe width="100%" height="100%" src="https://cpdevcp.cloudplusstaging.review/#/external-customer-signup-form?parentId=uniqueIdentifier&brandColor=%23uniqueColor" frameborder="0" seamless="seamless"></iframe>',
  imagePlaceholder: 'CloudPlus.Api/Static/Images/Placeholders/128x128.png',
  imagePlaceholderCircle: 'CloudPlus.Api/Static/Images/Placeholders/128x128circle.png',
  // Products Forms Settings
  productDetails: 'product-details',
  googleRecaptchaSiteKey: '6LfmTTMUAAAAAFdQzcGOC49mzUUpolN6WM3HhfGG',
  customerRole: 'CustomerAdmin',
  resellerRole: 'ResellerAdmin',
  masterRole: 'MasterAdmin',
  userRole: 'User',
  companyLogoUrl: 'https://cpstgcp.cloudplusstaging.review/CloudPlus.Api/Static/Images/CompanyLogo/',
};
