// <auto-generated />
namespace CloudPlus.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Office365Roles_AddDisplayNameAndOrd_Seed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Office365Roles_AddDisplayNameAndOrd_Seed));
        
        string IMigrationMetadata.Id
        {
            get { return "201802061503487_Office365Roles_AddDisplayNameAndOrd_Seed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
